### ISSUE TITLE
CA1416 warning when using version 5.0.0 of System.Security.Cryptography.ProtectedData

### ISSUE THREAD

**Issue by Thorarin** [integrativesoft/CrossProtectedData#3]
The API of the wrapper makes use of the `DataProtectionScope` directly.
The code analyzers for .NET 5 will complain about this:

`Warning	CA1416	This call site is reachable on all platforms. 'DataProtectionScope.CurrentUser' is only supported on: 'windows'.`

The current version of your package targets version 4.7.0 of the same package, so it will not appear unless a newer version is installed in the referencing project. Looking ahead, it may be a good idea to introduce a `CrossProtectScope` enum or something similar, so the wrapper is no longer using a type that is marked as Windows only.

**Comment by pablocar80** [comment]
@Thorarin is the code in this [PR](https://github.com/integrativesoft/CrossProtectedData/pull/4) what you had in mind?
